on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Run setup lint
        run: make setup-lint

      - name: Run linters
        run: make lint

      - name: Make sure there are no diffs
        run:
          git diff && exit $(git status --porcelain=v1
          2>/dev/null | wc -l)
